---
title: "Gene Ontology Analysis"
author: "Ann Murithi", "Fazihr Kayondo ""Ceren Ordas", "Stephen Gray", "Mercy Fakude"
date: "5/6/2022"
output: html_document
---

```{r}
#Install Packages For Analysis 
install.packages("ggplot2")
install.packages("tidyr")
install.packages("dplyr")
install.packages("tidyverse")
install.packages("ggpubr")
install.packages("patchwork")
install.packages("egg")
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggpubr)
library(patchwork)
library(egg)

```




```{r}
#Reading CSV file, Subsetting, and Merging Data for GO analysis 
gene_onto= read.csv("gene_ontology_dat.csv", fileEncoding = "UTF-8-BOM", header = T)

```

```{r}

#Data visulization
dim(gene_onto)
ls(gene_onto)
View(gene_onto)

```


```{r}
#Subsetting Data Based on Ontology Function 
gene_onto_subset= subset(gene_onto,select= c(EntrezID,Gene.Ontology,Function))
gene_onto_group= gene_onto_subset %>% group_by(Gene.Ontology)
GroupCount=gene_onto_group %>%
  count(Function)
GroupCount_Split=split(GroupCount, GroupCount$Gene.Ontology)
Biological=GroupCount_Split$Biological
Molecular=GroupCount_Split$Molecular
Cellular=GroupCount_Split$Cellular
```



```{r}
#Gene Ontology BarPlot
Bio=ggplot(data= Biological,aes(x=n, y=Function))+
  geom_bar(stat="identity",width = 0.3, fill="Blue")+
  ylab(NULL)+
  xlab(NULL)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
Mol=ggplot(data= Molecular,aes(x=n, y=Function))+
  geom_bar(stat="identity", width= 0.3,  fill="Yellow")+
  ylab("Gene Function")+
  xlab(NULL)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
Cell=ggplot(data= Cellular,aes(x=n, y=Function))+
  geom_bar(stat="identity", width = 0.3, fill="Brown")+
  ylab(NULL)+
  xlab("Number of Genes")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

ggarrange(Bio, Mol, Cell,
          labels = c("Bio","Mol","Cell"),
          ncol = 1, nrow = 3)

```

